### ISSUE TITLE
[EPIC] Grafana

### ISSUE THREAD

**Issue by rasheedamir** [stakater/bugs#133]
- [ ] dockerfile based on alpine with consul template #124 
- [ ] create automated build of dockerimage on dockerhub
- [ ] systemd unit
- [ ] healthcheck in consul #126 
- [ ] reconfigurable kairosdb datasource using consul template #128 
- [ ] reconfigurable prometheus datasource using consul template #123 
- [ ] evaluate wizzy #142
