### ISSUE TITLE
[EPIC] GoCD

### ISSUE THREAD

**Issue by rasheedamir** [stakater/bugs#136]
- [ ] Split blue green state update #131
- [ ] GoCd prevent data loss #130
- [ ] GoCD plugin for cleanup #122
- [ ] Pipeline to destroy admiral #120
- [ ] Destroy Blue Green group should also delete folders #119
- [ ] Use image tag instead of latest in cluster environment #117
- [ ] Create GoCD pipeline for shared lib #102
- [ ] Combine AMI creation for infra business apps for stage and prod #101
- [ ] Create pipeline for Java REST API based public facing app #159
- [ ] Create pipeline to deliver JavaScript based public facing frontend app #161
- [ ] Create pipeline for Java REST API based internal #160
