### ISSUE TITLE
[EPIC] Filebeat

### ISSUE THREAD

**Issue by hamza3202** [stakater/bugs#138]
- [ ] Filebeat reprocesses logs from start #139
- [ ] Add MongoDB logs to ELK #95
- [ ] Add MySQL logs to ELK #94 
- [x] Filebeat parse logs under subdirectories #163
- [ ] Filebeat with consul template logs issue #92
