### ISSUE TITLE
[THEME] Infrastructure Automation

### ISSUE THREAD

**Issue by rasheedamir** [stakater/bugs#146]
Everything related to VPC, networks, bastion hosts, terraform, etc.

- [ ] Cannot delete stage vpc #121
- [ ] Disable ssh access via password #112
- [ ] Keypairs are not delected when an environment is destroyed #164 
- [ ] Save terraform state in git #171
- [ ] Update to latest Terraform Version #64 
- [ ] Retry automatically if known issues occur while creating infrastructure #29
- [ ] Create S3 bucket to hold remote state through terraform as well #9 since we want to store it in Git so, we don't need to duplicate it #171 
- [ ] VPC peering connection disappear upon refreshing global admiral #4
- [ ] Deleting ELB with stickiness policy gives error #65
- [ ] Investigate and fix makefiles structure for copying .tf files #93
- [ ] Bastion host improvements #177
- [ ] Add retry on all downloads and uploads
- [ ] Spare subnets in each VPC
- [ ] In case of instance scale up, new instances are created and the application has not yet been initialized, so it does not treat that as healthy and a lot of instances area created on scaleup
- [ ] Dynamically fetch list for availability zones of a given region for current AWS account
- [ ] Discuss & clean up the tasks listed here: https://docs.google.com/document/d/12rWivB2KfDfs8ioG0oStywu4R4vmqnNeEKX3uXE3d40/edit#heading=h.63jef8d42iov
